lib/todo_list_web/router.ex
defmodule TodoListWeb.Router do
  use TodoListWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", TodoListWeb do
    pipe_through(:browser)

    get("/", PageController, :index)
    resources("/signin", SessionController, only: [:new, :create])
    resources("/signup", RegistrationController, only: [:new, :create])
    get("/sign_out", SessionController, :delete)

    resources "/todos", TodoController do
      resources("/items", ItemController, only: [:create])
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", TodoListWeb do
  #   pipe_through :api
  # end
end

lib/todo_list/todo.ex
defmodule TodoList.Todo do
  use Ecto.Schema
  import Ecto.Changeset

  alias TodoList.User
  alias TodoList.Todo.Item

  schema "todos" do
    field(:title, :string)
    belongs_to(:user, User)
    has_many(:items, Item)
    timestamps()
  end

  @doc false
  def changeset(todo, attrs) do
    todo
    |> cast(attrs, [:title, :user_id])
    |> validate_required([:title])
  end
end

lib/todo_list/todo/application.ex
defmodule TodoList.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      TodoList.Repo,
      # Start the endpoint when the application starts
      TodoListWeb.Endpoint
      # Starts a worker by calling: TodoList.Worker.start_link(arg)
      # {TodoList.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: TodoList.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    TodoListWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/todo_list/todo/item.ex
defmodule TodoList.Todo.Item do
  use Ecto.Schema
  import Ecto.Changeset

  alias TodoList.Todo

  schema "todo_items" do
    field(:item, :string)
    belongs_to(:todo, Todo)

    timestamps()
  end

  @doc false
  def changeset(item, attrs) do
    item
    |> cast(attrs, [:item, :todo_id])
    |> validate_required([:item])
  end
end

lib/todo_list_web/controllers/todo_controller.ex
defmodule TodoListWeb.TodoController do
  use TodoListWeb, :controller

  alias TodoList.Chat
  alias TodoList.Todo
  # alias TodoList.Repo
  alias TodoList.Todo.Item
  alias TodoList.Item.Items

  def index(conn, _params) do
    render(conn, "index.html")
  end

  def new(conn, _params) do
    changeset = Chat.change_todo(%Todo{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"todo" => todo_params}) do
    case Chat.create(todo_params) do
      {:ok, todo} ->
        conn
        |> put_session(:current_todo_id, todo.id)
        |> put_flash(:info, "Todo created successfully")
        |> redirect(to: Routes.page_path(conn, :index))

      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end


  def show(conn, %{"id" => id}) do
    todo = Items.get_todo!(id)
    items_changeset = Items.change_items(%Item{})
    render(conn, "show.html", content: todo, items_changeset: items_changeset)
  end

  def edit(conn, %{"id" => id}) do
    todo = Chat.get_todo!(id)
    changeset = Chat.change_todo(todo)
    render(conn, "edit.html", todo: todo, changeset: changeset)
  end

  def update(conn, %{"id" => id, "todo" => todo_params}) do
    todo = Chat.get_todo!(id)

    case Chat.update_todo(todo, todo_params) do
      {:ok, todo} ->
        conn
        |> put_flash(:info, "Todo updated successfully")
        |> redirect(to: Routes.todo_path(conn, :show, todo))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", todo: todo, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    todo = Chat.get_todo!(id)
    {:ok, _todo} = Chat.delete_todo(todo)

    conn
    |> put_flash(:info, "Todo deleted successfully")
    |> redirect(to: Routes.page_path(conn, :index))
  end
end

lib/todo_list_web/views/todo_view.ex
defmodule TodoListWeb.TodoView do
  use TodoListWeb, :view
end
Todo

lib/todo_list_web/templates/todo/edit.html.eex
<h2>Edit todo: <%= @todo.title %></h2>

<%= render "form.html", Map.put(assigns, :action, Routes.todo_path(@conn, :update, @todo)) %>

lib/todo_list_web/templates/todo/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
    <div class="form-label-group">
        <%= label f, :title, class: "control-label" %>
        <%= text_input f, :title, class: "form-control" %>
        <%= error_tag f, :title %>
    </div>

    <br>
       
    <div class="form-label-group">
        <%= submit "Create Todo" %>
    </div>
<% end %>
      

lib/todo_list_web/templates/todo/new.html.eex
<h2>New todo:</h2>

<%= render "form.html", Map.put(assigns, :action, Routes.todo_path(@conn, :create)) %>

lib/todo_list_web/templates/todo/show.html.eex
<h1>Name : <%= @content.title%></h1>


    <div class="right">
      <%= link "Edit", to: Routes.todo_path(@conn, :edit, @content.id) %>
        <br>
      <%= link "Delete", to: Routes.todo_path(@conn, :delete, @content), method: :delete, data: [confirm: "Are you sure?"] %>
    </div>

   <br>

<h3>Add Comment</h3>
  <%= form_for @items_changeset, Routes.todo_item_path(@conn, :create, @content), fn f ->%>
    <%= label f, :item %>
    <%= textarea f, :item %>
    <%= error_tag f, :item %>

    <h3>Comments</h3>
    <ul>

    <%= for items <- @content.items do %>
       <li class="item"><%= items.item%></li>
    <% end %>
    </li>
       
    <div class="form-label-group">
        <%= submit "Create Item" %>
    </div>

<% end %>