lib/todo_list_web/router.ex
defmodule TodoListWeb.Router do
  use TodoListWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", TodoListWeb do
    pipe_through(:browser)

    get("/", PageController, :index)
    resources("/signin", SessionController, only: [:new, :create])
    resources("/signup", RegistrationController, only: [:new, :create])
    get("/sign_out", SessionController, :delete)

    resources "/todos", TodoController do
      resources("/items", ItemController, only: [:create])
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", TodoListWeb do
  #   pipe_through :api
  # end
end

lib/todo_list_web/templates/page/index.html.eex
<div class="row">
  <div class="col-md-3">
    <h3>Todo</h3>
    <ul class="list-group">
    <%= for todo <- @todo do %>
      <li class="list-group-item"> <%= link todo.title, to: Routes.todo_path(@conn, :show, todo.id), class: "btn btn-link"%></li>
    <% end %>

    </ul>
  </div>
    <div class="jumbotron">
  <div class="col-md-9">
      <div class="page-header text-center">
        <h2>Welcome to Todo</h2>
      </div>
      <div class="page-header text-center">
        <h2><small>Choose the todo on the left to join</small></h2>
        <h2><small>or <a <%= link "Create", to: Routes.todo_path(@conn, :new), class: "btn btn-primary" %></a> a new one</small></h2>
      </div>
    </div>
  </div>
</div>